export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export type SEARCH_TEXT_CHANGED = typeof SEARCH_TEXT_CHANGED;

export const INCREMENT_MEDICINE = 'INCREMENT_MEDICINE';
export type INCREMENT_MEDICINE = typeof INCREMENT_MEDICINE;

export const DECREMENT_MEDICINE = 'DECREMENT_MEDICINE';
export type DECREMENT_MEDICINE = typeof DECREMENT_MEDICINE;
